server:
  port: 2020

spring:
  application:
    name: heimdall-config
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/shared
  profiles:
     active: native

security:
  user:
    password: heimdall

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2000/eureka/

logging:
  file: ./log/heimdall-config.log

